"on":
    push:
        branches:
            - main
name: Deploy to k8s-upgrade-tests
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: exec porter apply -f ./porter.yaml
              env:
                PORTER_APP_NAME: k8s-upgrade-tests
                PORTER_CLUSTER: "5313"
                PORTER_DEPLOYMENT_TARGET_ID: 2d6cbfdf-784c-46f8-8d88-c8d21fa1bc77
                PORTER_HOST: https://dashboard.porter.run
                PORTER_PR_NUMBER: ${{ github.event.number }}
                PORTER_PROJECT: "17878"
                PORTER_REPO_NAME: ${{ github.event.repository.name }}
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_17878_5313 }}
