"on":
    push:
        branches:
            - main
name: Deploy to k8s-upgrade-tests
jobs:
    porter-deploy:
        runs-on: ubicloud-standard-8
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: exec porter apply
              env:
                PORTER_APP_NAME: k8s-upgrade-tests
                PORTER_CLUSTER: "4437"
                PORTER_DEPLOYMENT_TARGET_ID: 49b1837b-a161-40fb-9145-27505210c03c
                PORTER_HOST: https://dashboard.porter.run
                PORTER_PR_NUMBER: ${{ github.event.number }}
                PORTER_PROJECT: "9267"
                PORTER_REPO_NAME: ${{ github.event.repository.name }}
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_9267_4437 }}
                DOCKER_BUILDKIT: 1
                PORTER_BUILDKIT_ARGS: --platform linux/amd64 --platform linux/arm64
